apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx-alpine
spec:
  containers:
  - image: nginx:1.29.6-alpine-slim
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
